---
# Syntax for no custom users:
#
# local_users: {}
# deleted_local_users:
#   - user1
#   - user2
#
# Syntax for specific users:
#
# deleted_local_users: []
# local_users:
#   user1:
#     firstname: first
#     lastname: last
#     pubkeys:
#       - 'ssh-rsa key1 comment'
#       - 'ssh-dsa key2 comment'
#
#     (optional:)
#     comment: "blablabla" (default is ANSIBLE MANGED USER)
#     createhome: yes|no (default is yes)
#     group: maingroup (must exist, if omit, will create/use <username> group
#     groups: [] (list of other groups to put user in)
#     home: /path/to/home/dir (default is /home/<username>)
#     shell: '/bin/zsh' (default is bash)
#     system: yes (default to no)
#     uid: 2000 (custom uid, default is deletaged to system)
#
#   user2:
#     ...

local_users:

  jganivet:
    uid: 4003
    firstname: Justin
    lastname: Ganivet

  lsamain:
    uid: 4002
    firstname: Lois
    lastname: Samain
    pubkeys:
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDA6YS+1B3MSeABhKCxDKVQnNYNlEEnrMMKIzCcdDXagYmJ6UfnHXTSpaf/6rIiy7XHxoBB48Z5fiV/ItArTaaInwvzY5uFJcZdc3uDGklAdDpT3HxYXHRzei4/jQ3W5/7GsWDYjGRz64yxcoZPg8TJDDNUhh22SBMJLQ4WLpvDT5OGxX/CR02cHvAapQLcH0LbUT+uD3l0+mhUAefliPnNrV5BmJOmav856yV9DDCrZcdj8f01e88yndgn9Z/V9JCt3afWXZFikvWTeEyxZU9ToinrXfVrj1dN2HuGKrZWuqRWhdJdywdec7VNa2LZDngX5buK2vtlfihHnE9YtA3F ypiolet@ovoid.void'

  mhotonnier:
    uid: 4001
    firstname: Morgan
    lastname: Hotonnier

  ypiolet:
    uid: 4000
    firstname: Youenn
    lastname: Piolet
    shell: "/bin/zsh"
    pubkeys:
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDA6YS+1B3MSeABhKCxDKVQnNYNlEEnrMMKIzCcdDXagYmJ6UfnHXTSpaf/6rIiy7XHxoBB48Z5fiV/ItArTaaInwvzY5uFJcZdc3uDGklAdDpT3HxYXHRzei4/jQ3W5/7GsWDYjGRz64yxcoZPg8TJDDNUhh22SBMJLQ4WLpvDT5OGxX/CR02cHvAapQLcH0LbUT+uD3l0+mhUAefliPnNrV5BmJOmav856yV9DDCrZcdj8f01e88yndgn9Z/V9JCt3afWXZFikvWTeEyxZU9ToinrXfVrj1dN2HuGKrZWuqRWhdJdywdec7VNa2LZDngX5buK2vtlfihHnE9YtA3F ypiolet@ovoid.void'
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9azn8qhO2QWKLCQj6aa4Q3iTHsczJqsZWOsNUpZVLWgm503K4zVJpjU3egCojXKRAQXOs4wpuqcE2QMzYNsgLyz1VzdPqRCxz3Bo2k9+spYQkEk0tuZO+S6WyGuZj3bRV+6wKJ5qe9vwy7YOUWY1N/Q5BgZmcM+55GnlWAYyp40Fnh8IMrZ4WHNKYsmDZgeTSDKCgC8cbKImonHAwX+5SGbdw814ArIY7g062UoFsxoh45bModPbzFt+8V3xbNqyOGZ0jtCl6Y1f7Es5QmuIzi4TngI6DauDiheI61Fh4kkpGPmkNmGPGffxIz2oNRMA/pORrzCpbvKtL3YbNkMWB ypiolet@thecore'

deleted_local_users: []
