---
# Syntax for no custom users:
#
# local_users: {}
# deleted_local_users:
#   - user1
#   - user2
#
# Syntax for specific users:
#
# deleted_local_users: []
# local_users:
#   user1:
#     firstname: first
#     lastname: last
#     pubkeys:
#       - 'ssh-rsa key1 comment'
#       - 'ssh-dsa key2 comment'
#
#     (optional:)
#     comment: "blablabla" (default is ANSIBLE MANGED USER)
#     createhome: yes|no (default is yes)
#     group: maingroup (must exist, if omit, will create/use <username> group
#     groups: [] (list of other groups to put user in)
#     home: /path/to/home/dir (default is /home/<username>)
#     shell: '/bin/zsh' (default is bash)
#     system: yes (default to no)
#     uid: 2000 (custom uid, default is deletaged to system)
#
#   user2:
#     ...

local_users:

  jganivet:
    uid: 4003
    firstname: Justin
    lastname: Ganivet

  lsamain:
    uid: 4002
    firstname: Lois
    lastname: Samain
    pubkeys:
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDA6YS+1B3MSeABhKCxDKVQnNYNlEEnrMMKIzCcdDXagYmJ6UfnHXTSpaf/6rIiy7XHxoBB48Z5fiV/ItArTaaInwvzY5uFJcZdc3uDGklAdDpT3HxYXHRzei4/jQ3W5/7GsWDYjGRz64yxcoZPg8TJDDNUhh22SBMJLQ4WLpvDT5OGxX/CR02cHvAapQLcH0LbUT+uD3l0+mhUAefliPnNrV5BmJOmav856yV9DDCrZcdj8f01e88yndgn9Z/V9JCt3afWXZFikvWTeEyxZU9ToinrXfVrj1dN2HuGKrZWuqRWhdJdywdec7VNa2LZDngX5buK2vtlfihHnE9YtA3F ypiolet@ovoid.void'

  mhotonnier:
    uid: 4001
    firstname: Morgan
    lastname: Hotonnier
    pubkeys:
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDcJ/u0mUKccMthdjwfCnh3xCJ9rKhjugb4Wm2hIMyZX/Q4su8zWYwcRCRJFgqhfNHd6L59LOK7yXed6VFwtf7Xu2WFV3kpJpp6hqFbfjeCqxUUp4hqtqV1bRiK3Y2lL4RgUaAGnDhj3Qw3c+skN608Iy5HxTASnCL/Wcln1J5tFqyAHtSryIr/1vKOC0oCUIecLh63SY2kW+73tWlWm767odCovVWlmSw0xDfj3qXqPy3ywNjOaCrPWALhs6uEmhZgvlX2AKMphqsjM6iMnB7svdjkUBS78caW0UW45FdI0/3jrdJUgWUXi7WdCjd72oxY4ydmRgFBIXffhMFEVq/lpoAyRTauf2TFKZvw+0mMcWBOOg5jZEfoIaM5gso6KNMeFbiHYWaT+s1Mvs1tc9vU56RNkvN2/S+l7cdIVjDAxVXtxba7pIWA+MbqR0XWg8Chr38pSUyLh7DLh6fq/BXNQPH294uzRwMUkj8TPBjZGPnUKZG+XRQS/192ABKXnQ3sQ94BKervzhkf/MPU38R1Kxkunfxe5FYKes/EyLyYAp5B4jHD2XKDfDlZcg0AzOR7fvVG2Y73w5NCURGrto0qi5AV9ae/1edklTQ8EiZkYDlg0ua6K/1Ce43L2kZGUGVXLOiA526OKdfkjP6loN2coVjGS4cpphO+5jEY2vMEBw== astorz@gmail.com'

  ypiolet:
    uid: 4000
    firstname: Youenn
    lastname: Piolet
    shell: "/bin/zsh"
    pubkeys:
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDA6YS+1B3MSeABhKCxDKVQnNYNlEEnrMMKIzCcdDXagYmJ6UfnHXTSpaf/6rIiy7XHxoBB48Z5fiV/ItArTaaInwvzY5uFJcZdc3uDGklAdDpT3HxYXHRzei4/jQ3W5/7GsWDYjGRz64yxcoZPg8TJDDNUhh22SBMJLQ4WLpvDT5OGxX/CR02cHvAapQLcH0LbUT+uD3l0+mhUAefliPnNrV5BmJOmav856yV9DDCrZcdj8f01e88yndgn9Z/V9JCt3afWXZFikvWTeEyxZU9ToinrXfVrj1dN2HuGKrZWuqRWhdJdywdec7VNa2LZDngX5buK2vtlfihHnE9YtA3F ypiolet@ovoid.void'
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9azn8qhO2QWKLCQj6aa4Q3iTHsczJqsZWOsNUpZVLWgm503K4zVJpjU3egCojXKRAQXOs4wpuqcE2QMzYNsgLyz1VzdPqRCxz3Bo2k9+spYQkEk0tuZO+S6WyGuZj3bRV+6wKJ5qe9vwy7YOUWY1N/Q5BgZmcM+55GnlWAYyp40Fnh8IMrZ4WHNKYsmDZgeTSDKCgC8cbKImonHAwX+5SGbdw814ArIY7g062UoFsxoh45bModPbzFt+8V3xbNqyOGZ0jtCl6Y1f7Es5QmuIzi4TngI6DauDiheI61Fh4kkpGPmkNmGPGffxIz2oNRMA/pORrzCpbvKtL3YbNkMWB ypiolet@thecore'

deleted_local_users: []
